"""Created messages

Revision ID: 21c7f1589cb7
Revises: b8441f497a14
Create Date: 2026-05-07 12:49:53.894855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c7f1589cb7'
down_revision: Union[str, Sequence[str], None] = 'b8441f497a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_messages_deal_id'), 'messages', ['deal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_deal_id'), table_name='messages')
    # ### end Alembic commands ###
